version: "3.7"

services:
  django_gunicorn:
    volumes:
    - static:/static
    - mediafiles:/mediafiles
    build: .
    ports:
      - 8000:8000    

    env_file: 
      - home/master/.env

  nginx:
    build: ./nginx
    volumes:
      #Nazwa volume oraz sciezka do folderu na host'cie
      - static:/static
      - mediafiles:/mediafiles
    ports:
      - 80:80    
    depends_on:
      - django_gunicorn

volumes:
  static:
  mediafiles:
  db:
